# Database of hostelworld.com.

DROP TABLE IF EXISTS HOSTEL;
DROP TABLE IF EXISTS BOOKING;
DROP TABLE IF EXISTS USER_PROF;
DROP TABLE IF EXISTS REVIEW;
DROP TABLE IF EXISTS FACILITIES;
DROP TABLE IF EXISTS LOCATION;
DROP TABLE IF EXISTS PHOTOS;
DROP TABLE IF EXISTS HOSTEL_LOCATION;
DROP TABLE IF EXISTS HOSTEL_FACILITIES;


CREATE TABLE HOSTEL (
    HOSTEL_ID       VARCHAR(5),
    HOSTEL_NAME     VARCHAR(45) CHARACTER SET UTF8MB4 NOT NULL,
    EMAIL           VARCHAR(45) CHARACTER SET UTF8MB4 UNIQUE,
    PHONE_NUM       VARCHAR(45) CHARACTER SET UTF8MB4,
    DESCRIPTION     VARCHAR(400) CHARACTER SET UTF8MB4,
    PRIMARY KEY(HOSTEL_ID) );


CREATE TABLE USER_PROF (
    USERNAME        VARCHAR(45),
    USER_FIRSTNAME  VARCHAR(45) CHARACTER SET UTF8MB4,
    USER_SURNAME    VARCHAR(45) CHARACTER SET UTF8MB4,
    USER_DOB        DATE NOT NULL,
    USER_NATIONALITY    VARCHAR(45),
    USER_NUMBER         VARCHAR(45),
    USER_EMAIL          VARCHAR(45) CHARACTER SET UTF8MB4 UNIQUE,
    USER_PHOTO          VARCHAR(45),
    PRIMARY KEY(USERNAME) );


CREATE TABLE BOOKING (
    BOOKING_REF VARCHAR(16),
    HOSTEL_ID   VARCHAR(5),
    USERNAME    VARCHAR(16) CHARACTER SET UTF8MB4,
    DATE_OF_BOOKING     DATE,
    DATE_OF_ARRVIAL     DATE,
    DATE_OF_DEPARTURE   DATE,
    PRIMARY KEY (BOOKING_REF),
    FOREIGN KEY (HOSTEL_ID) REFERENCES HOSTEL (HOSTEL_ID), 
    FOREIGN KEY (USERNAME) REFERENCES USER_PROF (USERNAME) );


    CREATE TABLE REVIEW  (
    REVIEW_ID   VARCHAR(20),
    HOSTEL_ID   VARCHAR(5),
    USERNAME    VARCHAR(16) CHARACTER SET UTF8MB4,
    VALUE_FOR_MONEY_SCORE   bit,
    STAFF_SCORE             bit,
    SECURITY_SCORE          bit,
    ATMOSPHERE_SCORE        bit,
    LOCATION_SCORE          bit,
    CLEANLINESS_SCORE       bit,
    FACILITIES_SCORE        bit,
    DATE_REVIEW             DATE,
    REVIEW_DESCRIPTION      VARCHAR(500),
    PRIMARY KEY (REVIEW_ID),
    FOREIGN KEY (HOSTEL_ID) REFERENCES HOSTEL (HOSTEL_ID),
    FOREIGN KEY (USERNAME) REFERENCES USER_PROF (USERNAME) );


CREATE TABLE PHOTOS (
    IMG_LINK    VARCHAR(150),
    HOSTEL_ID   VARCHAR(5),
    PRIMARY KEY (IMG_LINK), 
    FOREIGN KEY (HOSTEL_ID) REFERENCES HOSTEL (HOSTEL_ID) );

CREATE TABLE LOCATION (
    LONG_LAT    VARCHAR(100) CHARACTER SET UTF8MB4,
    REGION      VARCHAR(45),
    COUNTRY     VARCHAR(45),
    CITY        VARCHAR(45) CHARACTER SET UTF8MB4,
    ADDRESS     VARCHAR(100) CHARACTER SET UTF8MB4,
    PRIMARY KEY (LONG_LAT) );

CREATE TABLE HOSTEL_LOCATION (
    HOSTEL_ID   VARCHAR(5),
    LONG_LAT    VARCHAR(100) CHARACTER SET UTF8MB4,
    PRIMARY KEY (LONG_LAT, HOSTEL_ID),  
    FOREIGN KEY (HOSTEL_ID) REFERENCES HOSTEL (HOSTEL_ID),
    FOREIGN KEY (LONG_LAT) REFERENCES LOCATION (LONG_LAT) );


CREATE TABLE FACILITIES (
    FAC_ID          VARCHAR(5),
    FAC_NAME        VARCHAR(100),
    FAC_CATEGORY    VARCHAR(20),
    PRIMARY KEY (FAC_ID) );

CREATE TABLE HOSTEL_FACILITIES (
    FAC_ID      VARCHAR(5),
    HOSTEL_ID   VARCHAR(5),
    PRIMARY KEY (FAC_ID, HOSTEL_ID),
    FOREIGN KEY (FAC_ID) REFERENCES FACILITIES (FAC_ID),
    FOREIGN KEY (HOSTEL_ID) REFERENCES HOSTEL (HOSTEL_ID) );
    